// Generated by CoffeeScript 1.9.1
(function() {
  var Blocker, blocker;

  Blocker = (function() {
    function Blocker() {
      this.loggedIn = false;
      this.isWhitelist = false;
      this.list = [];
    }

    Blocker.prototype.getList = function() {
      return this.list;
    };

    Blocker.prototype.addSite = function(url) {
      return this.list.push(url);
    };

    Blocker.prototype.removeSite = function(url) {
      var index;
      index = this.list.indexOf(url);
      return this.list.splice(index, 1);
    };

    Blocker.prototype.isWhitelist = function() {
      return this.isWhitelist;
    };

    Blocker.prototype.block = function(url) {
      var bool;
      bool = this.list.includes(url);
      if (this.isWhitelist) {
        return !bool;
      } else {
        return bool;
      }
    };

    return Blocker;

  })();

  blocker = new Blocker;

  chrome.extension.getBackgroundPage().getUrl(function(tab) {
    if ((tab != null) && (tab.url != null)) {
      if (blocker.block(tab.url)) {
        return $('block-blocked').show();
      } else {
        return $('block-not-blocked').show();
      }
    }
  });

}).call(this);
