// Generated by CoffeeScript 1.9.1
(function() {
  var blocker, xhr;

  blocker = new Blocker();

  xhr = new XMLHttpRequest();

  this.getBlocker = function() {
    return blocker;
  };

  chrome.cookies.onChanged.addListener(function(removed, cookie, cause) {
    if (cookie.domain === "blocker.obscure.systems") {
      if (removed) {
        xhr.open("GET", "http", true);
        return xhr.onreadystatechange(function() {
          var newJson;
          if (xhr.readyState === 4) {
            return newJson = JSON.parse(xhr.responseText);
          }
        });
      }
    }
  });

  chrome.tabs.onCreated.addListener(function(tab) {
    return blocker.run(tab);
  });

  chrome.tabs.onActivated.addListener(function(info) {
    return chrome.tabs.get(info.tabId, function(tab) {
      return blocker.run(tab);
    });
  });

  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    if (changeInfo.status === 'loading') {
      return blocker.run(tab);
    }
  });

}).call(this);
