// Generated by CoffeeScript 1.9.1
(function() {
  var blocker, xhr;

  blocker = new Blocker();

  xhr = new XMLHttpRequest();

  this.getBlocker = function() {
    return blocker;
  };

  setInterval(function() {
    xhr.open("GET", "http://blocker.obscure.systems/get-todos", true);
    return xhr.onreadystatechange(function() {
      var newJson;
      if (xhr.readyState === 4) {
        return newJson = JSON.parse(xhr.responseText);
      }
    });
  }, 60000);

  chrome.tabs.onCreated.addListener(function(tab) {
    console.log("Hey!");
    return blocker.run(tab);
  });

  chrome.tabs.onActivated.addListener(function(info) {
    return chrome.tabs.get(info.tabId, function(tab) {
      console.log("Hey :/");
      return blocker.run(tab);
    });
  });

  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    if (changeInfo.status === 'loading') {
      console.log("Yo");
      return blocker.run(tab);
    }
  });

}).call(this);
