// Generated by CoffeeScript 1.9.1
(function() {
  var blocker;

  blocker = new Blocker();

  this.getBlocker = function() {
    return blocker;
  };

  chrome.cookies.onChanged.addListener(function(removed, cookie, cause) {});

  chrome.tabs.onCreated.addListener(function(tab) {});

  chrome.tabs.onActivated.addListener(function(info) {
    return chrome.tabs.get(info.tabId, function(tab) {});
  });

  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    if (changeInfo.status === 'loading') {

    }
  });

}).call(this);
