// Generated by CoffeeScript 1.9.1
(function() {
  var Blocker, constants;

  constants = {
    CREATE_USER: 'CREATE_USER',
    LOGIN_USER: 'LOGIN_USER'
  };

  Blocker = (function() {
    function Blocker() {
      this.loggedIn = false;
    }

    Blocker.prototype.login = function(username, pass) {
      this.username = username;
      return $.post("url");
    };

    return Blocker;

  })();

}).call(this);
