// Generated by CoffeeScript 1.9.1
(function() {
  var blocker;

  blocker = new Blocker();

  chrome.tabs.query({
    'active': true,
    'lastFocusedWindow': true
  }, function(tab) {
    var url;
    url = tab[0].url;
    if ((tab != null) && (url != null)) {
      console.log(url);
      $('#block-np').hide();
      if (blocker.block(url)) {
        return $('#block-blocked').show();
      } else {
        return $('#block-not-blocked').show();
      }
    }
  });

}).call(this);
