// Generated by CoffeeScript 1.9.1
(function() {
  var blocker;

  blocker = new Blocker();

  chrome.tabs.getCurrent(function(tab) {
    $('block-np').hide();
    if (blocker.block(tab.url)) {
      return $('block-blocked').show();
    } else {
      return $('block-not-blocked').show();
    }
  });

}).call(this);
